GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Kya mare tumhe?",
    "author" : "Ram",
    "url": "loarolala.com/ghochu",
    "likes": "7"
}