GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Bau muumhe?",
    "author" : "Rajkjkjm",
    "url": "loarolaljkjka.com/ghochu",
    "likes": "787",
    "userId": "63a28c0ce33830daf6b002c3"
}

###
DELETE http://localhost:3003/api/blogs/63920908f61be56b2db568e5

###
GET http://localhost:3003/api/blogs/639acbd402f6622dd6b11d4b

###
PUT http://localhost:3003/api/blogs/639acbd402f6622dd6b11d4b
Content-Type: application/json

{
    "likes" : "100"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username" : "Mswda",
    "name" : "Rasdasdja",
    "password" : "lalaRaja"
}

###
GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username" : "Mswda",
    "password" : "lalaRaja"
}