GET http://localhost:3000/api/persons

###
GET http://localhost:3000/api/person/63846590af988c6b00313ad7

###
GET http://localhost:3000/api/persons/info

###
PUT http://localhost:3000/api/persons/638735201f39f8b0287ae40d
Content-Type: application/json

{
    "name": "Koshe",
    "number": "1000"
}

###
POST http://localhost:3000/api/persons
Content-Type: application/json

{
    "name": "Rambo Uncle",
    "number": "98114545911"
}

###
DELETE http://localhost:3000/api/person/6384531287118e5d20aa7672